version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: docx-postgres
    environment:
      POSTGRES_DB: docxdb
      POSTGRES_USER: docx
      POSTGRES_PASSWORD: docxpass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - docx-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docx -d docxdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
  
  gotenberg:
    image: gotenberg/gotenberg:8
    environment:
      LIBREOFFICE_AUTO_START: "true"
      LIBREOFFICE_START_TIMEOUT: "60s"
      API_TIMEOUT: "120s"
    container_name: gotenberg
    command:
      - gotenberg
      - --api-port=3000
    networks:
      - docx-net
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped

  app:
    build: .
    container_name: docx-service
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    environment:
      DATABASE_URL: postgresql://docx:docxpass@docx-postgres:5432/docxdb
      DOCX_DIR: /mnt/docx
      PDF_DIR: /mnt/pdf
    volumes:
      - /srv/slr-docx:/mnt/docx
      - /srv/slr-pdf:/mnt/pdf
    networks:
      - docx-net
    restart: unless-stopped
    
  nginx:
    image: nginx:1.27-alpine
    container_name: docx-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - docx-net
    restart: unless-stopped

  worker:
    build: .
    container_name: docx-worker
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "worker:docx"]
    environment:
      DATABASE_URL: postgresql://docx:docxpass@docx-postgres:5432/docxdb
      DOCX_DIR: /mnt/docx
      WORKER_POLL_INTERVAL_MS: 3000
      WORKER_BATCH_SIZE: 1
    volumes:
      - /srv/slr-docx:/mnt/docx
    networks:
      - docx-net
    restart: unless-stopped
  
  
  
  pdf-worker:
    build: .
    container_name: pdf-worker
    depends_on:
      db:
        condition: service_healthy
      gotenberg:
        condition: service_healthy
    command: ["npm", "run", "worker:pdf"]
    environment:
      DATABASE_URL: postgresql://docx:docxpass@docx-postgres:5432/docxdb
      DOCX_DIR: /mnt/docx
      PDF_DIR: /mnt/pdf
      GOTENBERG_URL: http://gotenberg:3000
      WORKER_POLL_INTERVAL_MS: 3000
      WORKER_BATCH_SIZE: 1
    volumes:
      - /srv/slr-docx:/mnt/docx
      - /srv/slr-pdf:/mnt/pdf
    networks:
      - docx-net
    restart: unless-stopped


networks:
  docx-net:
    driver: bridge

volumes:
  db_data:
